SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SEDC.DifferentPizzaApp.BusinessLayer.Services.Interfaces;
using SEDC.DifferentPizzaApp.DataAccess;

namespace SEDC.DifferentPizzaApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            
            
            return View();
        }

        

    }
}

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Controllers/IngredientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SEDC.DifferentPizzaApp.BusinessLayer.Helpers;
using SEDC.DifferentPizzaApp.BusinessLayer.Mappings;
using SEDC.DifferentPizzaApp.BusinessLayer.Services.Interfaces;
using SEDC.DifferentPizzaApp.DataAccess;
using SEDC.DifferentPizzaApp.DataAccess.Core.Enums;
using SEDC.DifferentPizzaApp.DataAccess.ViewModels;

namespace SEDC.DifferentPizzaApp.Controllers
{
    public class IngredientController : Controller
    {
        private IIngredientService _ingredientService;
        public IngredientController(IIngredientService ingredientService)
        {
            _ingredientService = ingredientService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SelectDough()
        {
            var myList = _ingredientService.GetIngredientsByType(IngredientType.Dough);
            return View(myList);
        }

        [HttpPost]
        public IActionResult SelectDough(IngredientVM ingredient)
        {
            CurrentLogs.CurrentPizza.Ingredients.Add(IngredientMappers.FromIngredientVMToIngredient(ingredient));
            return RedirectToAction("SelectIngredients");
        }

        public IActionResult SelectIngredients()
        {
            var cheeseIngredients = _ingredientService.GetIngredientsByType(IngredientType.Cheese);
            return View(cheeseIngredients);
        }

        [HttpPost]
        public IActionResult SelectIngredients(List<IngredientVM> ingredients)
        {
            CurrentLogs.CurrentPizza.Ingredients.AddRange(IngredientMappers.FromIngredientVMsToIngredients(ingredients));
            return RedirectToAction("SelectIngredients2");
        }

        public IActionResult SelectIngredients2()
        {
            var meatIngredients = _ingredientService.GetIngredientsByType(IngredientType.Meat);
            return View(meatIngredients);
        }

        [HttpPost]
        public IActionResult SelectIngredients2(List<IngredientVM> ingredients)
        {
            CurrentLogs.CurrentPizza.Ingredients.AddRange(IngredientMappers.FromIngredientVMsToIngredients(ingredients));
            return RedirectToAction("MyOrder", "Order");
        }
    }
}

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SEDC.DifferentPizzaApp.BusinessLayer.Helpers;
using SEDC.DifferentPizzaApp.BusinessLayer.Mappings;
using SEDC.DifferentPizzaApp.BusinessLayer.Services.Interfaces;
using SEDC.DifferentPizzaApp.DataAccess;
using SEDC.DifferentPizzaApp.DataAccess.ViewModels;

namespace SEDC.DifferentPizzaApp.Controllers
{
    public class OrderController : Controller
    {
        private IOrderService _orderService;
        private IPizzaService _pizzaService;
        private IUserService _userService;
        public OrderController(IOrderService orderService, IPizzaService pizzaService, IUserService userService)
        {
            _orderService = orderService;
            _pizzaService = pizzaService;
            _userService = userService;
        }

        public IActionResult MyOrder()
        {
            var myPizza = _pizzaService.GetPizzaById(CurrentLogs.CurrentPizza.Id);
            var user = _userService.GetUserById(CurrentLogs.LoggedUser.Id);
            var myOrder = new OrderVM() { IsDelivered = false, OrderUser = user, Pizzas = new List<PizzaVM>() { myPizza } };
            var order = _orderService.CreateOrder(myOrder);
            CurrentLogs.CurrentOrder = OrderMappers.FromOrderVMToOrder(myOrder);
            return View(myOrder);
        }
    }
}

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Controllers/PizzaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SEDC.DifferentPizzaApp.BusinessLayer.Helpers;
using SEDC.DifferentPizzaApp.BusinessLayer.Mappings;
using SEDC.DifferentPizzaApp.BusinessLayer.Services.Interfaces;
using SEDC.DifferentPizzaApp.DataAccess;
using SEDC.DifferentPizzaApp.DataAccess.Core.Enums;
using SEDC.DifferentPizzaApp.DataAccess.ViewModels;

namespace SEDC.DifferentPizzaApp.Controllers
{
    public class PizzaController : Controller
    {
        private IPizzaService _pizzaService;
        public PizzaController(IPizzaService pizzaService)
        {
            _pizzaService = pizzaService;
        }
        public IActionResult Menu()
        {
            List<PizzaVM> ourPizzas = _pizzaService.GetAllPizzas();
        
            return View(ourPizzas);
        }

        public IActionResult MakePizza()
        {
            var pizzaSizes = new List<PizzaSize>();
            return View(pizzaSizes);
        }

        [HttpPost]
        public IActionResult MakePizza(PizzaSize size)
        {
            CurrentLogs.CurrentPizza.Size = size;
            return RedirectToAction("SelectDough", "Ingredient");
        }

        

       
    }
}

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SEDC.DifferentPizzaApp.BusinessLayer.Helpers;
using SEDC.DifferentPizzaApp.BusinessLayer.Mappings;
using SEDC.DifferentPizzaApp.BusinessLayer.Services.Interfaces;
using SEDC.DifferentPizzaApp.DataAccess;
using SEDC.DifferentPizzaApp.DataAccess.Core.Models;
using SEDC.DifferentPizzaApp.DataAccess.ViewModels;

namespace SEDC.DifferentPizzaApp.Controllers
{
    public class UserController : Controller
    {
        private IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        public IActionResult SignUp()
        {
            var user = new UserVM();
            return View(user);
        }

        [HttpPost]
        public IActionResult SignUp(UserVM user)
        {
            _userService.CreateUser(user);
            CurrentLogs.LoggedUser = UserMappers.FromUserVMToUser(user);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult LogIn()
        {
            var user = new UserVM();
            return View(user);
        }

        //[HttpPost]
        public IActionResult LogIn(UserVM user)
        {
            var loggedUser = _userService.LogInUser(user.Username, user.Password);
            if (loggedUser == null)
            {
                return RedirectToAction("LogIn");
            }
            CurrentLogs.LoggedUser = UserMappers.FromUserVMToUser(loggedUser);
            return RedirectToAction("Index", "Home");
        }

        
        public IActionResult LogOut()
        {
            CurrentLogs.LoggedUser = null;
            CurrentLogs.LoggedUser = new User();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult ViewUser()
        {
            var user = UserMappers.FromUserToUserVM(CurrentLogs.LoggedUser);
        

            return View(user);
        }

        
    }
}

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Views/Home/Index.cshtml
<style>
    .bg-1 { 
    background-color: #ec3237;	
    color: #ffffff;
    }
    .bg-2 { 
    background-color: #D3D3D3;
    color: #000000;
    }
    .bg-3 { 
    background-color: #ffffff;
    color: #555555;
    }
    .container-fluid {
    padding-top: 30px;
    padding-bottom: 30px;
    }
</style>
<div class="container-fluid bg-1 text-center">
    <h2 class="margin">Tired of eating the same pizza every time?</h2>
    <img src="~/images/Logo.jpg" class="img-rounded margin" style="display:inline" width="350" height="350">
    <h2>We have the solution!</h2>
</div>
<div class="container-fluid bg-2 text-center">
    <h3 class="margin">What are we offering?</h3>
    <p>If you have a specific taste, don't wait! With us you can create your own pizza, and if you like it, order it again as many times as you want!</p>
    <p>See some examples of our pizzas below:</p>
    <a asp-controller="Pizza" asp-action="Menu" class="btn btn-default btn-lg">
         Our Pizzas
    </a>
</div>
<div class="container-fluid bg-3 text-center">
    <h3 class="margin">How to get it?</h3><br>
    <div class="row">
        <div class="col-sm-4">
            <p>Register for your account now! Or just log in if you have been here before!</p>
            <img src="~/images/1.png" class="img-responsive margin" style="width:100%">
        </div>
        <div class="col-sm-4">
            <p>Make your own pizza or choose one of our favorites!</p>
            <img src="~/images/2.png" class="img-responsive margin" style="width:100%">
        </div>
        <div class="col-sm-4">
            <p>Make the order and wait for it to be delivered or pick it up at our store!</p>
            <img src="~/images/3.png" class="img-responsive margin" style="width:100%">
        </div>
    </div>
</div>

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Views/Ingredient/SelectDough.cshtml
@model List<IngredientVM>


<h2>SelectDough</h2>
<div class="form-group">
    <label for="size">Select the type of dough for your pizza: </label>
    <select class="form-control" id="size">
        @foreach (var item in Model)
        {
            <option>@item</option>
        }

    </select>
</div>

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Views/Ingredient/SelectIngredients.cshtml
@model List<IngredientVM>



<h2>Select Cheeses</h2>

<div class="form-group">
    <label for="size">Select the type of cheese for your pizza: </label>
    <select class="form-control" id="size">
        @foreach (var item in Model)
        {

            <option>@item.Name</option>
        }

        </select>


        <form asp-action="SelectIngredients">
            <input type="submit" value="Submit" class="btn btn-default" /> |
            <a asp-action="Index" asp-controller="Home">Back to Home</a>
        </form>
</div>

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Views/Ingredient/SelectIngredients2.cshtml
@model  List<IngredientVM>


<h2>Select Meat</h2>

<div class="form-group">
    <label for="size">Select the type of meat for your pizza: </label>
    <select class="form-control" id="size">
        @foreach (var item in Model)
        {

            <option>@item.Name</option>
        }

    </select>


    <form asp-action="SelectIngredients">
        <input type="submit" value="Submit" class="btn btn-default" /> |
        <a asp-controller="Home" asp-action="Index">Back to Home</a>
    </form>
</div>

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Views/Pizza/MakePizza.cshtml
@model  List<PizzaSize>
<p>Please select the size of your pizza:</p>
<style>
    .mydiv{
        color:black;
        background-color:brown;
    }
</style>


<div class="form-group mydiv" >
    <label for="size">Select the size of your pizza: </label>
    <select class="form-control" id="size">
        @foreach (var item in Enum.GetNames(typeof(PizzaSize))
        {
            <option>@item</option>
        }
        
    </select>
</div>

<a asp-controller="Pizza" asp-action="SelectDough" class="btn btn-secondary btn-lg" role="button" aria-pressed="true">Continue</a>

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Views/Pizza/Menu.cshtml
@model PizzaVM
@{
    ViewData["Title"] = "Menu";
}

<h2>Menu</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ingredients)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

</table>

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Views/Shared/_Layout.cshtml
@{ var isLogged = false;
        if (CurrentLogs.LoggedUser.Username != null)
        {
            isLogged = true;
        }
        ViewBag.IsLogged = isLogged;
        ViewBag.Username = CurrentLogs.LoggedUser.Username; }

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SEDC.DifferentPizzaApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <style>
        .navbar {
            padding-top: 10px;
            padding-bottom: 10px;
            border: 0;
            border-radius: 0;
            margin-bottom: 0;
            font-size: 12px;
            letter-spacing: 5px;
            background-color: #FF6347;
            color: black;
        }

        .navbar-nav li a:hover {
            color: #000000;
        }

        body {
            font: 20px Montserrat, sans-serif;
            line-height: 1.8;
            color: #f5f6f7;
        }

        p {
            font-size: 16px;
        }

        .margin {
            margin-bottom: 45px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Home</a>
                @if (ViewBag.IsLogged)
                {
                    <a class="navbar-brand" asp-controller="Pizza" asp-action="Menu">Our Pizzas</a>
                    <a class="navbar-brand" asp-controller="Pizza" asp-action="MakePizza">Make Your Pizza</a>
                    <a class="navbar-brand" asp-controller="Order" asp-action="ViewOrders">Orders</a>
                }
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    @if (!ViewBag.IsLogged)
                    {
                        <li><a asp-controller="User" asp-action="SignUp"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        <li><a asp-controller="User" asp-action="LogIn"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="User" asp-action="ViewUser">@ViewBag.Username</a></li>
                        <li><a asp-controller="User" asp-action="LogOut">Log Out</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - SEDC.DifferentPizzaApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Views/User/LogIn.cshtml
@model UserVM


<div class="row">
    <div class="col-md-4">
        <form asp-action="LogIn">
            
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="LogIn" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Views/User/SignUp.cshtml
@model UserVM

<style>
    div{
        color:darkcyan;
    }
</style>

<div class="row">
    <div class="col-md-4">
        <form asp-action="SignUp">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" required/>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" required/>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" type="number" required/>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" required/>
            </div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" required/>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" required/>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Back to Home</a>
</div>

SEDC.DifferentPizzaApp/SEDC.DifferentPizzaApp/Views/User/ViewUser.cshtml
@*@model SEDC.DifferentPizzaApp.Models.ViewModels.UserVM

@{
    ViewData["Title"] = "ViewUser";
}

<h2>ViewUser</h2>

<div>
    <h4>UserVM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
</div>*@